-- final version
UPDATE public.airports SET country_name = 'EG' WHERE id = 38;
UPDATE public.airports SET country_name = 'BS' WHERE id = 2272;
UPDATE public.airports SET country_name = 'IN' WHERE id = 1273;
UPDATE public.airports SET country_name = 'PE' WHERE id = 1875;
UPDATE public.airports SET country_name = 'KR' WHERE id = 196;
UPDATE public.airports SET country_name = 'BS' WHERE id = 1639;
UPDATE public.airports SET country_name = 'US' WHERE id = 2681;
UPDATE public.airports SET country_name = 'MD' WHERE id = 202;
UPDATE public.airports SET country_name = 'CO' WHERE id = 2644;
UPDATE public.airports SET country_name = 'ID' WHERE id = 129;
UPDATE public.airports SET country_name = 'MY' WHERE id = 2249;
UPDATE public.airports SET country_name = 'VG' WHERE id = 2131;
UPDATE public.airports SET country_name = 'MY' WHERE id = 1692;
UPDATE public.airports SET country_name = 'GW' WHERE id = 1453;
UPDATE public.airports SET country_name = 'CN' WHERE id = 1573;
UPDATE public.airports SET country_name = 'CV' WHERE id = 1656;
UPDATE public.airports SET country_name = 'IL' WHERE id = 1218;
UPDATE public.airports SET country_name = 'JP' WHERE id = 1898;
UPDATE public.airports SET country_name = 'CA' WHERE id = 2699;
UPDATE public.airports SET country_name = 'FJ' WHERE id = 1664;
UPDATE public.airports SET country_name = 'MY' WHERE id = 2464;
UPDATE public.airports SET country_name = 'JP' WHERE id = 988;
UPDATE public.airports SET country_name = 'CH' WHERE id = 629;
UPDATE public.airports SET country_name = 'PH' WHERE id = 2798;
UPDATE public.airports SET city_name = 'Reyes Acozac', country_name = 'MX' WHERE id = 5342;
UPDATE public.airports SET city_name = 'Araripina', country_name = 'BR' WHERE id = 5343;
UPDATE public.airports SET city_name = 'Iguatu', country_name = 'BR' WHERE id = 5352;
UPDATE public.airports SET city_name = 'Costa Marques', country_name = 'BR' WHERE id = 5355;
UPDATE public.airports SET city_name = 'Lages', country_name = 'BR' WHERE id = 5362;
UPDATE public.airports SET country_name = 'BR' WHERE id = 5371;
UPDATE public.airports SET city_name = 'Teofilo Otoni', country_name = 'BR' WHERE id = 5345;
UPDATE public.airports SET city_name = 'Sulaymaniyah', country_name = 'IQ' WHERE id = 5347;
UPDATE public.airports SET city_name = 'Arbil', country_name = 'IQ' WHERE id = 5348;
UPDATE public.airports SET city_name = 'Basrah', country_name = 'IQ' WHERE id = 5349;
UPDATE public.airports SET city_name = 'Ariquemes', country_name = 'BR' WHERE id = 5356;
UPDATE public.airports SET city_name = 'Salinopolis', country_name = 'BR' WHERE id = 5358;
UPDATE public.airports SET country_name = 'KH' WHERE id = 2865;
UPDATE public.airports SET city_name = 'Chitose / Tomakomai', country_name = 'JP' WHERE id = 5360;
UPDATE public.airports SET country_name = 'BR' WHERE id = 5363;
UPDATE public.airports SET country_name = 'IN' WHERE id = 3149;
UPDATE public.airports SET country_name = 'BR' WHERE id = 5372;
UPDATE public.airports SET country_name = 'MY' WHERE id = 3283;
UPDATE public.airports SET city_name = 'Eirunepe', country_name = 'BR' WHERE id = 5698;
UPDATE public.airports SET city_name = 'Porto Alegre', country_name = 'BR' WHERE id = 5339;
UPDATE public.airports SET city_name = 'Tulum', country_name = 'MX' WHERE id = 5340;
UPDATE public.airports SET city_name = 'Baghdad', country_name = 'IQ' WHERE id = 5350;
UPDATE public.airports SET city_name = 'Pimenta Bueno', country_name = 'BR' WHERE id = 5354;
UPDATE public.airports SET country_name = 'VU' WHERE id = 3342;
UPDATE public.airports SET city_name = 'Paranavai', country_name = 'BR' WHERE id = 5357;
UPDATE public.airports SET city_name = 'Garanhuns', country_name = 'BR' WHERE id = 5359;
UPDATE public.airports SET city_name = 'Teixeira De Freitas', country_name = 'BR' WHERE id = 5341;
UPDATE public.airports SET city_name = 'Manicore', country_name = 'BR' WHERE id = 5361;