UPDATE public.airports SET city_name = 'Garanhuns', country_name = 'BR' WHERE id = 6479;
UPDATE public.airports SET city_name = 'Salinopolis', country_name = 'BR' WHERE id = 6478;
UPDATE public.airports SET city_name = 'Tulum', country_name = 'MX' WHERE id = 6485;
UPDATE public.airports SET city_name = 'Porto Alegre', country_name = 'BR' WHERE id = 6484;
UPDATE public.airports SET city_name = 'Lages', country_name = 'BR' WHERE id = 6483;
UPDATE public.airports SET city_name = 'Manicore', country_name = 'BR' WHERE id = 6481;
UPDATE public.airports SET city_name = 'Chitose / Tomakomai', country_name = 'JP' WHERE id = 6480;
UPDATE public.airports SET city_name = 'Paranavai', country_name = 'BR' WHERE id = 6477;
UPDATE public.airports SET city_name = 'Ariquemes', country_name = 'BR' WHERE id = 6476;
UPDATE public.airports SET city_name = 'Costa Marques', country_name = 'BR' WHERE id = 6475;
UPDATE public.airports SET city_name = 'Pimenta Bueno', country_name = 'BR' WHERE id = 6474;
UPDATE public.airports SET city_name = 'Iguatu', country_name = 'BR' WHERE id = 6472;
UPDATE public.airports SET city_name = 'Baghdad', country_name = 'IQ' WHERE id = 6470;
UPDATE public.airports SET city_name = 'Basrah', country_name = 'IQ' WHERE id = 6469;
UPDATE public.airports SET city_name = 'Arbil', country_name = 'IQ' WHERE id = 6468;
UPDATE public.airports SET city_name = 'Sulaymaniyah', country_name = 'IQ' WHERE id = 6467;
UPDATE public.airports SET city_name = 'Teofilo Otoni', country_name = 'BR' WHERE id = 6465;
UPDATE public.airports SET city_name = 'Araripina', country_name = 'BR' WHERE id = 6463;
UPDATE public.airports SET city_name = 'Reyes Acozac', country_name = 'MX' WHERE id = 6462;
UPDATE public.airports SET city_name = 'Teixeira De Freitas', country_name = 'BR' WHERE id = 6461;
UPDATE public.airports SET city_name = 'Eirunepe', country_name = 'BR' WHERE id = 6259;
UPDATE public.airports SET country_name = 'BR' WHERE id = 5933;
UPDATE public.airports SET country_name = 'BR' WHERE id = 5932;
UPDATE public.airports SET country_name = 'BR' WHERE id = 5924;
UPDATE public.airports SET country_name = 'CA' WHERE id = 3927;
UPDATE public.airports SET country_name = 'US' WHERE id = 3909;
UPDATE public.airports SET country_name = 'CO' WHERE id = 3872;
UPDATE public.airports SET country_name = 'VU' WHERE id = 3760;
UPDATE public.airports SET country_name = 'MY' WHERE id = 3681;
UPDATE public.airports SET country_name = 'IN' WHERE id = 3525;
UPDATE public.airports SET country_name = 'KH' WHERE id = 3155;
UPDATE public.airports SET country_name = 'PH' WHERE id = 3073;
UPDATE public.airports SET country_name = 'MY' WHERE id = 2909;
UPDATE public.airports SET country_name = 'BS' WHERE id = 2680;
UPDATE public.airports SET country_name = 'MY' WHERE id = 2651;
UPDATE public.airports SET country_name = 'VG' WHERE id = 2498;
UPDATE public.airports SET country_name = 'JP' WHERE id = 2222;
UPDATE public.airports SET country_name = 'PE' WHERE id = 2195;
UPDATE public.airports SET country_name = 'MY' WHERE id = 1977;
UPDATE public.airports SET country_name = 'FJ' WHERE id = 1942;
UPDATE public.airports SET country_name = 'CV' WHERE id = 1929;
UPDATE public.airports SET country_name = 'BS' WHERE id = 1905;
UPDATE public.airports SET country_name = 'CN' WHERE id = 1827;
UPDATE public.airports SET country_name = 'GW' WHERE id = 1679;
UPDATE public.airports SET country_name = 'IN' WHERE id = 1452;
UPDATE public.airports SET country_name = 'IL' WHERE id = 1380;
UPDATE public.airports SET country_name = 'JP' WHERE id = 1102;
UPDATE public.airports SET country_name = 'CH' WHERE id = 719;
UPDATE public.airports SET country_name = 'MD' WHERE id = 270;
UPDATE public.airports SET country_name = 'KR' WHERE id = 262;
UPDATE public.airports SET country_name = 'ID' WHERE id = 170;
UPDATE public.airports SET country_name = 'EG' WHERE id = 46;