UPDATE public.airports SET city_name = '', country_name = '' WHERE id = 6473;
UPDATE public.airports SET city_name = '', country_name = '' WHERE id = 6471;
UPDATE public.airports SET city_name = '', country_name = '' WHERE id = 6466;
UPDATE public.airports SET city_name = '', country_name = '' WHERE id = 6464;
UPDATE public.airports SET country_name = '' WHERE id = 3684;
UPDATE public.airports SET country_name = '' WHERE id = 3480;
UPDATE public.airports SET country_name = '' WHERE id = 3067;
UPDATE public.airports SET country_name = '' WHERE id = 3058;
UPDATE public.airports SET country_name = '' WHERE id = 3012;
UPDATE public.airports SET country_name = '' WHERE id = 3001;
UPDATE public.airports SET country_name = '' WHERE id = 2989;
UPDATE public.airports SET country_name = '' WHERE id = 2666;
UPDATE public.airports SET country_name = '' WHERE id = 2468;
UPDATE public.airports SET country_name = '' WHERE id = 2245;
UPDATE public.airports SET country_name = '' WHERE id = 2231;
UPDATE public.airports SET country_name = '' WHERE id = 1994;
UPDATE public.airports SET country_name = '' WHERE id = 1980;
UPDATE public.airports SET country_name = '' WHERE id = 1637;
UPDATE public.airports SET country_name = '' WHERE id = 1218;