-- Updating country_name for airports
UPDATE public.airports SET country_name = 'France' WHERE id = 2794;
UPDATE public.airports SET country_name = 'Indonesia' WHERE id = 1919;
UPDATE public.airports SET country_name = 'China' WHERE id = 2723;
UPDATE public.airports SET country_name = 'Papua New Guinea' WHERE id = 1087;
UPDATE public.airports SET country_name = 'Brazil' WHERE id = 2733;
UPDATE public.airports SET country_name = 'United Kingdom' WHERE id = 1695;
UPDATE public.airports SET country_name = 'Monaco' WHERE id = 2261;
UPDATE public.airports SET country_name = 'Oman' WHERE id = 1423;
UPDATE public.airports SET country_name = 'Saudi Arabia' WHERE id = 2744;
UPDATE public.airports SET country_name = 'British Virgin Islands' WHERE id = 1907;
UPDATE public.airports SET country_name = 'British Virgin Islands' WHERE id = 2107;
UPDATE public.airports SET country_name = 'South Korea' WHERE id = 1709;
UPDATE public.airports SET country_name = 'France' WHERE id = 2787;
UPDATE public.airports SET country_name = 'Bahamas' WHERE id = 3111;
UPDATE public.airports SET city_name = 'Paracatu', country_name = 'Brazil' WHERE id = 5344;
UPDATE public.airports SET city_name = 'Apuí', country_name = 'Brazil' WHERE id = 5351;
UPDATE public.airports SET city_name = 'Sobral', country_name = 'Brazil' WHERE id = 5346;
UPDATE public.airports SET city_name = ' São Benedito', country_name = 'Brazil' WHERE id = 5353;
UPDATE public.airports SET country_name = 'British Virgin Islands' WHERE id = 3286;
